### ISSUE TITLE
Can't follow README or tutorial

### ISSUE THREAD

**Issue by dpo** [bbopt/NOMAD.jl#15]
The instructions in the README appear to be outdated. So does the tutorial. A simple up-to-date example with a constraint or two and installation instructions would be very useful. I looked in the NOMAD4 branch, but no success there either :-(.

**Comment by amontoison** [comment]
We are working on a new release for NOMAD4 with @salomonl. We had multiple problems with parralel evaluations at the C level (https://github.com/amontoison/nomad/pull/1 and https://github.com/amontoison/nomad/pull/2) and the last build with Yggdrasil breaks everything on NOMAD4 branch....

The README and the tutorial shouldn't be outdated for the master branch. Do you need NOMAD 4 or NOMAD 3.9.1 suit you? I can quickly fix a compilation bug on Mac if it's what you need.

**Comment by amontoison** [comment]
I see the problem, Cxx wasn't updated for julia 1.4 : https://github.com/JuliaInterop/Cxx.jl/pull/465. Cxx only works for julia 1.1, 1.2 and 1.3....

@salomonl what is the best solution for NOMAD 3.9.1, I can build it on Yggdrasil but the C interface for NOMAD4 will not work?

**Comment by salomonl** [comment]
@amontoison Yes infortunatelly it will not work, as the C linking code is not included in Nomad3.9.1. There are two possibilities. I can make a C interface for nomad 3.9.1 but it will take me a bit of time before it can be done (and there will be not parallelism). Or we have to wait until the CXX.jl issue is fixed. 

Do you really need it quickly @dpo ?

**Comment by dpo** [comment]
No, I don't need it urgently. I mostly wanted to alert you. I lost Alexis's Jupyter notebook from the tutorial session and without it, I realized I couldn't even get started.

**Comment by amontoison** [comment]
Thanks Ludovic, I don't think we should spend time on nomad 3.9.1. Let's hope that cxx.jl package be fixed quickly for julia 1.4.
I will rebuild nomad 4 without parallelism today and send you again the Jupyter notebook @dpo . We will update documentation and tutorial as soon as the parallel version of nomad 4 is working.

**Comment by amontoison** [comment]
I fixed NOMAD4 branch and I sent you the notebook on Slack.

**Comment by salomonl** [comment]
Thanks Alexis !

**Comment by amontoison** [comment]
@dpo 
We updated NOMAD.jl, it uses by default NOMAD4 precompiled now.
The documentation and the README have been updated too.
