### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by shoshievass** [bbopt/NOMAD.jl#17]
When I try to Pkg.add("NOMAD"), I get the following error. Might you know what's going on?

![image](https://user-images.githubusercontent.com/3093378/83186080-d121e780-a0e0-11ea-9249-502613b06364.png)

**Comment by amontoison** [comment]
`Cxx.jl` is not working with Julia 1.4, is it this version of Julia that you are using?
Cxx.jl and NOMAD.jl shoud work fine on julia 1.3.

**Comment by amontoison** [comment]
@shoshievass We just release a new version of NOMAD.jl that do not depend on Cxx.jl. It should work fine on julia 1.4 now.
