### ISSUE TITLE
How to add minimum mesh size?

### ISSUE THREAD

**Issue by sivabkumar** [bbopt/NOMAD.jl#24]
How to specify minimum mesh size in nomad.jl

**Comment by salomonl** [comment]
Hey @sivabkumar ,

Infortunately, this parameter is not accessible to the user in the Julia interface. You have to use the C++ version for the moment if you want to play with this parameter. If you really want to get a stopping criteria, use the `max_bb_eval` parameter.

**Comment by amontoison** [comment]
@sivabkumar we are working on an update of the interface, it will possible in the future to give use any option available in the NOMAD4 solver.

**Comment by amontoison** [comment]
@sivabkumar We updated the C interface. You can specify the minimum mesh size with the release `2.1.0`.

**Comment by sivabkumar** [comment]
Sir,Thanks for your effort. 
Regards 
Dr. B. Sivakumar Ph.D., Assistant Professor, Department of Applied Mathematics and Statistics, School of Mathematics, Madurai Kamaraj University, Madurai - 625 021, Tamilnadu, India. Mobile: +91 98942 27177 

    On Wednesday, February 17, 2021, 11:23:28 PM GMT+5:30, Alexis <notifications@github.com> wrote:  
 
 


@sivabkumar We updated the C interface. You can specify the minimum mesh size with the release 2.1.0.

**Comment by amontoison** [comment]
fixed by #32
