### ISSUE TITLE
`max_time` as an integer

### ISSUE THREAD

**Issue by tmigot** [bbopt/NOMAD.jl#50]
Usually in Julia, the `time()` is a real number. Is there any specific reason why the `max_time` in `NomadOption` is fixed as an integer here, [L.69](https://github.com/bbopt/NOMAD.jl/blob/9fb0fdbd343cafd000f67e2c3502d97d67e36842/src/core.jl#L69)?

**Comment by salomonl** [comment]
Hey @tmigot . `max_time` is a parameter of the Nomad software given in seconds, which can be provided as a `size_t` type for the c++ interface (see https://nomad-4-user-guide.readthedocs.io/en/latest/Appendix.html `MAX_TIME` parameter).

**Comment by tmigot** [comment]
Ok, thanks. I just got confused because in the `NomadOptions` it is specified:
```
max_time::Union{Nothing, Int}
```
