### ISSUE TITLE
Relationship between the granularity and the min_mesh_size of a NomadProblem

### ISSUE THREAD

**Issue by MonssafToukal** [bbopt/NOMAD.jl#58]
I would like to know if there is a relationship between the granularity  and the `min_mesh_size` of a NomadProblem. I am currently trying to increase the granularity of real variables, but if I do so, should I also change the mesh size  `min_mesh_size`?

**Comment by salomonl** [comment]
The granularity is always bigger or equal to the `min_mesh_size`. Another point is that if if you reach the target granularity, Nomad will only stop after consuming the whole budget of evaluations. If you want to stop it faster, I think it is better to tune the `min_mesh_size` parameter than the granularity parameter. If you have integer or binary variables, it is better to declare their types than to set the granularity.
